export const STAT_DEFINITIONS = {
  'Real CAGR':         'Compound Annual Growth Rate — the annualized return over the full backtest period, assuming gains are reinvested each year.',
  'CAGR':              'Compound Annual Growth Rate — the annualized return over the full backtest period, assuming gains are reinvested each year.',
  'Sharpe Ratio':      'Return above the risk-free rate (4.5%/yr) divided by total volatility. Higher means better risk-adjusted performance.',
  'Sharpe':            'Return above the risk-free rate (4.5%/yr) divided by total volatility. Higher means better risk-adjusted performance.',
  'Max Drawdown':      'The largest peak-to-trough drop in portfolio value during the backtest. Shows the worst-case loss an investor would have experienced.',
  'Max DD':            'The largest peak-to-trough drop in portfolio value during the backtest. Shows the worst-case loss an investor would have experienced.',
  'Sortino Ratio':     'Like the Sharpe ratio, but only penalizes downside volatility — months where the portfolio lost money. Upside swings are ignored.',
  'Sortino':           'Like the Sharpe ratio, but only penalizes downside volatility — months where the portfolio lost money. Upside swings are ignored.',
  'Best Year':         'The highest annual return in any calendar year during the backtest.',
  'Worst Year':        'The lowest annual return in any calendar year during the backtest.',
  '10-Year CAGR':      'Annualized return over the most recent 10 years of data only — useful for comparing recent performance.',
  '10yr CAGR':         'Annualized return over the most recent 10 years of data only — useful for comparing recent performance.',
  'Ulcer Index':       'Measures the depth and duration of drawdowns. Lower is better — a high score means the portfolio spent a long time deep in losses.',
  'Ulcer Perf. Index': 'Return divided by Ulcer Index. Like a Sharpe ratio that only penalizes sustained drawdowns, not brief dips.',
  'UPI':               'Return divided by Ulcer Index. Like a Sharpe ratio that only penalizes sustained drawdowns, not brief dips.',
  'GFC CAGR':          'Annualized return during the Global Financial Crisis (Dec 2007 – Feb 2009). Shows how the portfolio held up in a severe crash.',
  'Dot-com CAGR':      'Annualized return during the Dot-com crash (Mar 2000 – Oct 2002). Shows how the portfolio held up during a prolonged equity bear market.',
  'Dotcom CAGR':       'Annualized return during the Dot-com crash (Mar 2000 – Oct 2002). Shows how the portfolio held up during a prolonged equity bear market.',
  'Rolling Returns':   'Returns measured over every possible rolling window in the backtest. Low/Avg/High show the range of outcomes an investor could have experienced depending on when they started.',
};
